name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: |-
          ~/.cache/pip
          .venv
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('./paleae/pyproject.toml') }}
        restore-keys: |-
          ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-
          ${{ runner.os }}-python-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Security scan with bandit
      run: |
        bandit -r paleae.py

    - name: Check code formatting with ruff
      run: |
        ruff format --check .

    - name: Lint with ruff
      run: |
        ruff check .

    - name: Type check with mypy
      run: |
        mypy .

    - name: Check docstrings with pydocstyle
      run: |
        pydocstyle paleae.py

    - name: Test with pytest and coverage
      run: |
        pytest --cov=paleae --cov-report=xml --cov-report=term-missing
        pytest --cov=paleae --cov-fail-under=80

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: PaulTiffany/paleae
