name: Release to PyPI

on:
  workflow_dispatch: # Allows manual triggering from GitHub UI
  push:
    tags:
      - 'v*.*.*' # Triggers on pushes to tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use latest Python 3

    - name: Install build and publish dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |-
          See the [CHANGELOG.md](https://github.com/PaulTiffany/paleae/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
          
          Full Source: [${{ github.ref_name }}.zip](https://github.com/PaulTiffany/paleae/archive/refs/tags/${{ github.ref_name }}.zip)
        draft: false
        prerelease: false
